@startuml diagram
title Data Pipeline
footer Disponível em https://github.com/caiquefirefox/dbre-mackenzie-lab01

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_TOP_DOWN()

Person(user, "Usuário")
Person(user_business, "Usuário de negócios")

System_Boundary(oltp, "oltp"){
    Container(frontend, "Frontend", "Angular", "WepApp de interação")
    Container(api, "API", "Java")
    ContainerDb(db, "Database", "Oracle")
}

System_Boundary(data_sources, "Fonte de dados externas"){
    Container(ibge, "API IBGE")
    ContainerDb(correio, "Geo", "csv")
    ContainerDb(erp, "ERP", "SQL Server", "Protheus")
    ContainerQueue(iot, "Sensores", "Armazem de distribuição")
    Container(scraping, "Web scraping")
    Container(pdf, "PDF's")
}

System_Boundary(olap, "olap"){
    Container(extraction, "Ingestão de Dados")
    Container(transformation, "Transformação de dados")
    Container(load, "Carga de Dados")

    ContainerDb(object_storage, "Object Storage", "S3/Blob/GCS/Minio")
    ContainerDb(raw, "Bronze", "BigQuery/SnowFlake/Redshift/Exadata")
    ContainerDb(silver, "Silver", "BigQuery/SnowFlake/Redshift/Exadata")
    ContainerDb(dw, "Gold", "BigQuery/SnowFlake/Redshift/Exadata")    
    
    Rel(extraction, raw, "Salvar dados da origem")
    Rel(raw, transformation, "Transformar dados da RAW")
    Rel(transformation, silver, "Salvar dados transformados")

    Rel(silver, load, "Carregar dados da SILVER")
    Rel(load, dw, "Salvar dados da raw")
    Rel(extraction, object_storage, "Salvar arquivos")
}

System_Boundary(analytics, "Analytics"){
    Container(dataviz, "Data Viz", "PowerBi/Tableau")
    Container(ml, "Machine Learning", "Predições/Segmentações")
}

Rel(user, frontend, "Realizar pedidos")
Rel(user_business, dataviz, "Obter insights")

Rel(frontend, api, "Consumir endpoints")
Rel(api, db, "Persistir dados")
Rel(db, extraction, "Carregar dados da origem")
Rel(ibge, extraction, "Carregar dados da origem")
Rel(correio, extraction, "Carregar dados da origem")
Rel(iot, extraction, "Carregar dados da origem")
Rel(erp, extraction, "Carregar dados da origem")
Rel(scraping, extraction, "Carregar dados da origem")
Rel(pdf, extraction, "Carregar dados da origem")
Rel(dw, dataviz, "Alimentar dados para dashboards e insights")
BiRel(dw, ml, "Treinar modelos de machine learning")

@enduml